name: Bench output summary

on:
  issue_comment:
    types: created

jobs:
  Produce_bench_summary:
    name: Post bench summary
    if: (github.event.issue.pull_request != 'null') && (startsWith(github.event.comment.body, 'Here are the [benchmark results]'))
    runs-on: ubuntu-latest
    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v3.1.1/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> "${GITHUB_PATH}"

      - uses: actions/checkout@v4
        with:
          ref: master
          sparse-checkout: |
            scripts/bench.sh
            Mathlib/tp.lean

      - name: Summarize bench output
        run: |
          comment="$(./scripts/bench.sh "${PR}" scripts/bench_summary.lean)"
          #cat Mathlib/tp.lean | lake env lean --stdin
          printf 'Posting to PR #%s\n%s\n' "${PR}" "${comment}"
          printf 'bench_tally<<EOF\n%s\nEOF' "${comment}" >> "$GITHUB_OUTPUT"
        env:
          PR:  ${{ github.event.issue.number }}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
