name: Auto-bench

on:
  pull_request:
    types: [opened]  # This triggers the action when the PR is opened.

jobs:
  automatic_first_bench:
    runs-on: ubuntu-latest

    steps:
      - name: Add comment to PR
        uses: GrantBirki/comment@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ! **mangled** bench

            This is an automated bench-marking that runs when a PR is opened. No need to repeat.
